Repository Eldar2021/my_quran, pull requests merged in 2023-06, with the labels that each got.

#104 Upgrade flutter and dart versions
  .github/workflows/analyze_test.yml
  .github/workflows/build_android.yml
  .github/workflows/build_ios.yml
  .github/workflows/ci_android.yml
  .github/workflows/ci_ios.yml
  README.md
  app/android/app/build.gradle
  app/android/build.gradle
  app/ios/Podfile.lock
  app/ios/Runner.xcodeproj/project.pbxproj
  app/lib/app/services/app_service.dart
  app/lib/bootstrap.dart
  app/lib/constants/assets/assets.gen.dart
  app/pubspec.lock
  app/pubspec.yaml
  app/test_driver/app.dart
  packages/mq_client/pubspec.yaml
  packages/mq_storage/pubspec.yaml
  pubspec.lock
  pubspec.yaml
Labels: A2-technical, B1-medium, C0-breaksnothing

#112 Upgrade flutter version and dependencies versions
  .github/workflows/analyze_test.yml
  .github/workflows/build_android.yml
  .github/workflows/build_ios.yml
  .github/workflows/ci_android.yml
  .github/workflows/ci_ios.yml
  README.md
  app/ios/Podfile.lock
  app/pubspec.lock
  app/pubspec.yaml
  packages/mq_client/pubspec.yaml
  packages/mq_storage/pubspec.yaml
  pubspec.lock
  pubspec.yaml
Labels: A2-technical, B2-priority, C0-breaksnothing

#115 Fix horizontal space & Migrate to Dart 3 (part 01)
  app/lib/app/logic/app_cubit.dart
  app/lib/app/logic/auth_cubit.dart
  app/lib/app/router/app_router.dart
  app/lib/app/services/app_service.dart
  app/lib/app/services/auth_service.dart
  app/lib/app/services/theme_service.dart
  app/lib/constants/app/app_const.dart
  app/lib/core/client/network_client.dart
  app/lib/core/client/remote_client.dart
  app/lib/core/launch/app_launch.dart
  app/lib/models/juz/juz_model.dart
  app/lib/models/juz/juz_surah_model.dart
  app/lib/models/quran_page/filters.dart
  app/lib/models/quran_page/meta.dart
  app/lib/models/quran_page/quran_page.dart
  app/lib/models/quran_page/verse.dart
  app/lib/models/surah/surah_model.dart
  app/lib/modules/read/logic/read_theme_cubit.dart
  app/lib/theme/custom/color/app_colors.dart
  app/lib/theme/custom/color/custom_color.dart
  app/lib/theme/custom/typography/quran_font_family.dart
  app/lib/utils/show/alerts.dart
  app/lib/utils/show/sheets.dart
  app/lib/utils/show/snackbars.dart
  app/test/widget_test.dart
Labels: A1-bugfix, B2-priority, C0-breaksnothing

#116 Statics readed-reading-unsellected
  app/lib/models/hatim/hatim_juz.dart
  app/lib/modules/home/view/hatim_view.dart
  app/lib/modules/home/widgets/juz_percent_widget.dart
  app/lib/modules/home/widgets/widgets.dart
Labels: A0-ux, B1-medium, C0-breaksnothing

#117 Sign in ui is done
  app/analysis_options.yaml
  app/lib/app/router/app_router.dart
  app/lib/constants/api/api_const.dart
  app/lib/l10n/arb/app_ar.arb
  app/lib/l10n/arb/app_en.arb
  app/lib/l10n/arb/app_id.arb
  app/lib/l10n/arb/app_kk.arb
  app/lib/l10n/arb/app_ky.arb
  app/lib/l10n/arb/app_ru.arb
  app/lib/l10n/arb/app_tr.arb
  app/lib/modules/login/login.dart
  app/lib/modules/login/view/login_view.dart
  app/lib/modules/login/view/sign_in_view.dart
  app/pubspec.lock
  app/pubspec.yaml
Labels: A0-ux, B0-low, C0-breaksnothing

#118 El/contact us
  app/assets/icons/contact_us.svg
  app/lib/app/router/app_router.dart
  app/lib/constants/assets/assets.gen.dart
  app/lib/core/launch/app_launch.dart
  app/lib/l10n/arb/app_ar.arb
  app/lib/l10n/arb/app_en.arb
  app/lib/l10n/arb/app_id.arb
  app/lib/l10n/arb/app_kk.arb
  app/lib/l10n/arb/app_ky.arb
  app/lib/l10n/arb/app_ru.arb
  app/lib/l10n/arb/app_tr.arb
  app/lib/modules/settings/settings.dart
  app/lib/modules/settings/view/contact_us.dart
  app/lib/modules/settings/view/settings_view.dart
  app/lib/modules/settings/widgets/contact_us_card.dart
  app/lib/modules/settings/widgets/social_icon_button.dart
  app/lib/modules/settings/widgets/widgets.dart
Labels: A2-technical, B1-medium, C0-breaksnothing
