Repository Eldar2021/my_quran, pull requests merged in 2023-04, with the labels that each got.

#81 Added check-labels github-actions
  .github/workflows/check_labels.yml
  .github/workflows/draft_release.yml
Labels: A2-technical, B1-medium, C0-breaksnothing

#83 Bump app version v0.0.1
  app/pubspec.yaml
Labels: A2-technical, B0-low, C0-breaksnothing

#84 Fix release template
  .github/release_template.yml
Labels: A1-bugfix, B2-priority, C0-breaksnothing

#87 fixed hatim page text
  app/lib/modules/home/view/hatim_select_page_view.dart
Labels: A0-ux, B2-priority, C0-breaksnothing

#88 Fix check icon
  app/lib/modules/home/view/hatim_select_page_view.dart
  app/lib/modules/home/view/hatim_view.dart
Labels: A1-bugfix, B2-priority, C0-breaksnothing

#93 multi font family for read page finished
  app/lib/constants/app/app_const.dart
  app/lib/l10n/arb/app_ar.arb
  app/lib/l10n/arb/app_en.arb
  app/lib/l10n/arb/app_id.arb
  app/lib/l10n/arb/app_kk.arb
  app/lib/l10n/arb/app_ky.arb
  app/lib/l10n/arb/app_ru.arb
  app/lib/l10n/arb/app_tr.arb
  app/lib/modules/read/logic/read_theme_cubit.dart
  app/lib/modules/read/logic/read_theme_state.dart
  app/lib/modules/read/services/read_theme_service.dart
  app/lib/modules/read/view/pagination_view.dart
  app/lib/modules/read/view/read_view.dart
  app/lib/theme/custom/typography/quran_font_family.dart
  app/lib/utils/show/sheets.dart
Labels: A0-ux, B1-medium, C1-breaksapi

#95 Add `bismallah` to begin surah
  app/lib/constants/app/app_const.dart
  app/lib/models/quran_page/quran_page.dart
  app/lib/models/quran_page/verse.dart
  app/lib/modules/read/view/pagination_view.dart
  app/lib/modules/read/view/read_view.dart
Labels: A0-ux, B0-low, C0-breaksnothing

#96 Bump app version v0.0.2
  app/pubspec.yaml
Labels: A2-technical, B2-priority, C0-breaksnothing
