Repository Eldar2021/my_quran, pull requests merged in 2023-08, with the labels that each got.

#138 Bump flutter and dependencies versions
  .github/workflows/analyze_test.yml
  .github/workflows/build_android.yml
  .github/workflows/build_ios.yml
  .github/workflows/ci_android.yml
  .github/workflows/ci_ios.yml
  README.md
  app/ios/Podfile.lock
  app/pubspec.lock
  app/pubspec.yaml
  packages/mq_client/pubspec.yaml
  packages/mq_storage/pubspec.yaml
  pubspec.lock
  pubspec.yaml
Labels: A2-technical, B0-low, C0-breaksnothing

#139 Update Quran font
  app/assets/fonts/qpc_uthmanic_hafs/qpc_uthmanic_hafs.otf
  app/lib/constants/api/api_const.dart
  app/lib/constants/assets/fonts.gen.dart
  app/lib/constants/contants.dart
  app/lib/models/quran_page/quran_page.dart
  app/lib/models/quran_page/verse.dart
  app/lib/models/quran_page/verse.g.dart
  app/lib/modules/read/logic/read_cubit.dart
  app/lib/modules/read/logic/read_state.dart
  app/lib/modules/read/logic/read_theme_cubit.dart
  app/lib/modules/read/logic/read_theme_state.dart
  app/lib/modules/read/read.dart
  app/lib/modules/read/services/read_service.dart
  app/lib/modules/read/services/read_theme_service.dart
  app/lib/modules/read/view/pagination_view.dart
  app/lib/modules/read/view/read_view.dart
  app/lib/theme/custom/typography/quran_font_family.dart
  app/pubspec.lock
  app/pubspec.yaml
Labels: A0-ux, B1-medium, C0-breaksnothing

#140 Use repository provider instead get it
  app/lib/app/view/app_view.dart
  app/lib/core/client/remote_client.dart
  app/lib/locator.dart
  app/lib/main.dart
  app/lib/modules/home/view/hatim_view.dart
  app/lib/modules/read/view/read_view.dart
  app/pubspec.lock
  app/pubspec.yaml
Labels: A2-technical, B1-medium, C0-breaksnothing

#141 Added `UIBackgroundModes` to `info.plist`
  app/ios/Runner/Info.plist
Labels: A1-bugfix, B1-medium, C0-breaksnothing

#142 Added `x-juz` to read quran by juz
  app/lib/modules/quran/view/page_view_item.dart
Labels: A0-ux, B0-low, C0-breaksnothing

#144 Release v1.1.1
  .github/ISSUE_TEMPLATE/release-testing.md
  app/android/app/build.gradle
  app/ios/Runner.xcodeproj/project.pbxproj
  app/pubspec.yaml
Labels: A2-technical, B0-low, C0-breaksnothing

#145 Replace alternative gender icon
  app/assets/icons/male.svg
  app/pubspec_overrides.yaml
Labels: A0-ux, B1-medium, C0-breaksnothing

#147 Upgrade flutter 3.13.0
  .github/workflows/analyze_test.yml
  .github/workflows/build_android.yml
  .github/workflows/build_ios.yml
  .github/workflows/ci_android.yml
  .github/workflows/ci_ios.yml
  README.md
  app/ios/Runner.xcodeproj/project.pbxproj
  app/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  app/lib/models/juz/juz_data.dart
  app/lib/models/surah/surah_data.dart
  app/lib/modules/home/view/hatim_view.dart
  app/lib/modules/read/view/read_view.dart
  app/lib/utils/show/alerts.dart
  app/pubspec.lock
  app/pubspec.yaml
  pubspec.lock
  pubspec.yaml
Labels: A2-technical, B1-medium, C0-breaksnothing

#148 Fix UI `BottomSheet`
  app/lib/modules/read/view/read_view.dart
  app/lib/utils/show/sheets.dart
Labels: A0-ux, B0-low, C0-breaksnothing

#149 Fix quran audio UX
  app/lib/app/view/app_view.dart
  app/lib/components/audio/audio_center_button.dart
  app/lib/components/audio/seek_bar.dart
  app/lib/modules/quran_audio/logic/quran_audio_cubit.dart
  app/lib/modules/quran_audio/quran_audio.dart
  app/lib/modules/quran_audio/view/quran_audio_view.dart
  app/lib/modules/quran_audio/widgets/audio_borrom_sheet.dart
Labels: A0-ux, B1-medium, C0-breaksnothing

#150 CI screenshots multi devices (Refactoring Integration Test)
  app/lib/components/card/select_lang_list.dart
  app/lib/modules/home/view/hatim_view.dart
  app/lib/modules/home/view/home_view.dart
  app/lib/modules/login/view/login_view.dart
  app/lib/modules/login/widget/select_gender.dart
  app/lib/modules/login/widget/select_lang.dart
  app/lib/modules/main/view/main_view.dart
  app/lib/modules/quran/view/page_view_item.dart
  app/lib/modules/quran/view/quran_view.dart
  app/lib/modules/quran_audio/view/quran_audio_view.dart
  app/lib/modules/quran_audio/widgets/audio_borrom_sheet.dart
  app/lib/modules/read/view/pagination_view.dart
  app/lib/modules/read/view/read_view.dart
  app/lib/modules/settings/view/about_us.dart
  app/lib/modules/settings/view/contact_us.dart
  app/lib/modules/settings/view/developers_view.dart
  app/lib/modules/settings/view/gender_settings.dart
  app/lib/modules/settings/view/lang_settings.dart
  app/lib/modules/settings/view/settings_view.dart
  app/lib/modules/settings/view/theme_settings.dart
  app/pubspec.lock
  app/pubspec.yaml
  app/pubspec_overrides.yaml
  app/test_driver/app/app.dart
  app/test_driver/app/hatim/hatim_test.dart
  app/test_driver/app/home/home_test.dart
  app/test_driver/app/login/login_test.dart
  app/test_driver/app/navigation.dart
  app/test_driver/app/quran_audio/quran_audio_test.dart
  app/test_driver/app/quran_read/quran_read_test.dart
  app/test_driver/app/settings/settings_test.dart
  app/test_driver/app_test.dart
  app/test_driver/extensions/extensions.dart
  app/test_driver/extensions/screenshot_driver.dart
  app/test_driver/extensions/screenshot_name.dart
  app/test_driver/helpers/add_delay.dart
  app/test_driver/helpers/functions/take_screenshot.dart
  app/test_driver/helpers/helpers.dart
  packages/mq_ci_keys/.gitignore
  packages/mq_ci_keys/analysis_options.yaml
  packages/mq_ci_keys/lib/mq_ci_keys.dart
  packages/mq_ci_keys/lib/src/mq_ci_keys_base.dart
  packages/mq_ci_keys/pubspec.yaml
  packages/mq_ci_keys/test/mq_ci_keys_base_test.dart
Labels: A2-technical, B1-medium, C0-breaksnothing

#153 Quran audio auto next play
  app/lib/app/view/app_view.dart
  app/lib/models/surah/surah_model.dart
  app/lib/modules/quran_audio/logic/quran_audio_cubit.dart
  app/lib/modules/quran_audio/logic/quran_audio_state.dart
  app/lib/modules/quran_audio/view/quran_audio_view.dart
  app/lib/modules/quran_audio/widgets/audio_borrom_sheet.dart
  app/pubspec.lock
  app/pubspec.yaml
Labels: A2-technical, B1-medium, C0-breaksnothing

#155 Release v1.2.0
  app/android/app/build.gradle
  app/ios/Runner.xcodeproj/project.pbxproj
  app/pubspec.yaml
  app/pubspec_overrides.yaml
Labels: A2-technical, B1-medium, C0-breaksnothing
