Repository Eldar2021/my_quran, pull requests merged in 2023-07, with the labels that each got.

#120 Ui juz bug fixed
  app/lib/bootstrap.dart
  app/lib/modules/home/widgets/juz_percent_widget.dart
Labels: A1-bugfix, B0-low, C0-breaksnothing

#122 Bump dependencies
  app/android/build.gradle
  app/ios/Podfile.lock
  app/lib/l10n/arb/app_ar.arb
  app/lib/modules/home/widgets/juz_percent_widget.dart
  app/pubspec.lock
  app/pubspec.yaml
  melos.yaml
  packages/mq_storage/pubspec.yaml
Labels: A2-technical, B2-priority, C0-breaksnothing

#127 Quran audio
  app/android/app/build.gradle
  app/android/app/src/main/AndroidManifest.xml
  app/android/app/src/main/res/xml/network_security_config.xml
  app/ios/Podfile.lock
  app/ios/Runner/Info.plist
  app/lib/app/view/app_view.dart
  app/lib/components/audio/audio_center_button.dart
  app/lib/components/audio/seek_bar.dart
  app/lib/components/components.dart
  app/lib/constants/api/api_const.dart
  app/lib/l10n/arb/app_ar.arb
  app/lib/l10n/arb/app_en.arb
  app/lib/l10n/arb/app_id.arb
  app/lib/l10n/arb/app_kk.arb
  app/lib/l10n/arb/app_ky.arb
  app/lib/l10n/arb/app_ru.arb
  app/lib/l10n/arb/app_tr.arb
  app/lib/modules/main/logic/main_cubit.dart
  app/lib/modules/main/view/main_view.dart
  app/lib/modules/modules.dart
  app/lib/modules/quran/view/quran_view.dart
  app/lib/modules/quran_audio/logic/quran_audio_cubit.dart
  app/lib/modules/quran_audio/logic/quran_audio_state.dart
  app/lib/modules/quran_audio/quran_audio.dart
  app/lib/modules/quran_audio/view/quran_audio_detail.dart
  app/lib/modules/quran_audio/view/quran_audio_view.dart
  app/lib/modules/settings/view/settings_view.dart
  app/lib/theme/custom/component/componet_theme.dart
  app/lib/utils/reg_exp/app_reg_exp.dart
  app/lib/utils/show/alerts.dart
  app/lib/utils/urils.dart
  app/pubspec.lock
  app/pubspec.yaml
Labels: A0-ux, B1-medium, C0-breaksnothing

#128 My quran audio background
  app/android/app/src/main/AndroidManifest.xml
  app/android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/ios/Podfile.lock
  app/ios/Runner/Info.plist
  app/lib/main.dart
  app/lib/modules/quran_audio/logic/quran_audio_cubit.dart
  app/pubspec.lock
  app/pubspec.yaml
Labels: A2-technical, B1-medium, C0-breaksnothing

#133 Added home page localization
  app/lib/l10n/arb/app_ar.arb
  app/lib/l10n/arb/app_en.arb
  app/lib/l10n/arb/app_id.arb
  app/lib/l10n/arb/app_kk.arb
  app/lib/l10n/arb/app_ru.arb
Labels: A1-bugfix, B0-low, C0-breaksnothing
