Repository Eldar2021/my_quran, pull requests merged in 2024-01, with the labels that each got.

#178 Bump f3.16.5
  .github/workflows/analyze_test.yml
  .github/workflows/build_android.yml
  .github/workflows/build_ios.yml
  .github/workflows/ci_android.yml
  .github/workflows/ci_ios.yml
  README.md
  app/ios/Podfile.lock
  app/pubspec.lock
  app/pubspec.yaml
  packages/mq_ci_keys/pubspec.yaml
  packages/mq_client/pubspec.yaml
  packages/mq_storage/pubspec.yaml
  pubspec.lock
  pubspec.yaml
Labels: A2-technical, B1-medium, C0-breaksnothing

#179 Fix ayah symbol
  app/lib/models/quran_page/quran_page.dart
Labels: A0-ux, B1-medium, C0-breaksnothing

#180 Create FUNDING
  .github/FUNDING.yml
Labels: A2-technical, B0-low, C0-breaksnothing

#181 Bump flutter v3.16.8
  .github/workflows/analyze_test.yml
  .github/workflows/build_android.yml
  .github/workflows/build_ios.yml
  .github/workflows/ci_android.yml
  .github/workflows/ci_ios.yml
  README.md
  app/ios/Flutter/AppFrameworkInfo.plist
  app/ios/Podfile.lock
  app/ios/Runner.xcodeproj/project.pbxproj
  app/lib/modules/home/view/home_view.dart
  app/pubspec.lock
  app/pubspec.yaml
  packages/mq_ci_keys/pubspec.yaml
  packages/mq_client/pubspec.yaml
  packages/mq_storage/pubspec.yaml
  pubspec.lock
  pubspec.yaml
Labels: A2-technical, B1-medium, C0-breaksnothing

#182 Fixed crash screenshot CI on IOS
  .github/workflows/ci_android.yml
  .github/workflows/ci_ios.yml
  README.md
  app/test_driver/extensions/screenshot_driver.dart
  melos.yaml
Labels: A2-technical, B2-priority, C0-breaksnothing

#183 Created Web
  app/.metadata
  app/lib/modules/home/view/home_view.dart
  app/web/favicon.png
  app/web/icons/app_icon.png
  app/web/icons/launcher_icon copy 2.png
  app/web/icons/launcher_icon copy 3.png
  app/web/icons/launcher_icon copy 4.png
  app/web/icons/launcher_icon copy.png
  app/web/icons/launcher_icon.png
  app/web/index.html
  app/web/manifest.json
Labels: A0-ux, B1-medium, C0-breaksnothing

#185 Bump fv3.16.9
  .github/workflows/analyze_test.yml
  .github/workflows/build_android.yml
  .github/workflows/build_ios.yml
  .github/workflows/ci_android.yml
  .github/workflows/ci_ios.yml
  app/pubspec.lock
  app/pubspec.yaml
  packages/mq_storage/pubspec.yaml
  pubspec.lock
  pubspec.yaml
Labels: A0-ux, B1-medium, C0-breaksnothing
