Repository Eldar2021/my_quran, pull requests merged in 2024-03, with the labels that each got.

#190 Change home architecture
  app/analysis_options.yaml
  app/lib/app/view/app_view.dart
  app/lib/models/hatim/hatim_read_model.dart
  app/lib/models/hatim/hatim_read_model.g.dart
  app/lib/models/home/home_model.dart
  app/lib/models/models.dart
  app/lib/modules/hatim/logic/hatim_read/hatim_read_cubit.dart
  app/lib/modules/home/data/data.dart
  app/lib/modules/home/data/model/home_model_response.dart
  app/lib/modules/home/data/model/home_model_response.g.dart
  app/lib/modules/home/data/repository/home_repository.dart
  app/lib/modules/home/data/source/home_local_data_source.dart
  app/lib/modules/home/data/source/home_remote_data_source.dart
  app/lib/modules/home/domain/domain.dart
  app/lib/modules/home/domain/entity/home_model.dart
  app/lib/modules/home/domain/repository/home_repository.dart
  app/lib/modules/home/domain/usecase/get_data_usecase.dart
  app/lib/modules/home/home.dart
  app/lib/modules/home/logic/home_cubit.dart
  app/lib/modules/home/presentation/cubit/home_cubit.dart
  app/lib/modules/home/presentation/cubit/home_state.dart
  app/lib/modules/home/presentation/presentation.dart
  app/lib/modules/home/presentation/view/home_view.dart
  app/lib/modules/home/presentation/widgets/home_card.dart
  app/lib/modules/home/service/home_service.dart
  app/test/helpers/pump_app.dart
  app/test/widget_test.dart
Labels: A2-technical, B2-priority, C0-breaksnothing

#193 Release v1.3.0
  CHANGELOG.md
  app/android/app/build.gradle
  app/ios/Runner.xcodeproj/project.pbxproj
  app/pubspec.yaml
Labels: A2-technical, B2-priority, C0-breaksnothing

#195 Bump flutter
  .github/workflows/analyze_test.yml
  .github/workflows/build_android.yml
  .github/workflows/build_ios.yml
  .github/workflows/ci_android.yml
  .github/workflows/ci_ios.yml
  README.md
  app/ios/Podfile.lock
  app/ios/Runner.xcodeproj/project.pbxproj
  app/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  app/pubspec.lock
  app/pubspec.yaml
  packages/mq_ci_keys/pubspec.yaml
  packages/mq_client/pubspec.yaml
  packages/mq_storage/pubspec.yaml
  pubspec.lock
  pubspec.yaml
Labels: A2-technical, B1-medium, C0-breaksnothing

#199 change settings module architecture
  app/lib/modules/settings/presentation/presentation.dart
  app/lib/modules/settings/presentation/view/about_us.dart
  app/lib/modules/settings/presentation/view/contact_us.dart
  app/lib/modules/settings/presentation/view/developers_view.dart
  app/lib/modules/settings/presentation/view/gender_settings.dart
  app/lib/modules/settings/presentation/view/lang_settings.dart
  app/lib/modules/settings/presentation/view/settings_view.dart
  app/lib/modules/settings/presentation/view/theme_settings.dart
  app/lib/modules/settings/presentation/widgets/contact_us_card.dart
  app/lib/modules/settings/presentation/widgets/social_icon_button.dart
  app/lib/modules/settings/presentation/widgets/widgets.dart
  app/lib/modules/settings/settings.dart
Labels: A1-bugfix, B1-medium, C0-breaksnothing

#200 change main and dev_mode architecture
  app/lib/modules/dev_mode/dev_mode.dart
  app/lib/modules/dev_mode/presentation/dev_mode_view.dart
  app/lib/modules/main/main.dart
  app/lib/modules/main/presentation/main_view.dart
Labels: A1-bugfix, B1-medium, C0-breaksnothing

#201 change login architecture
  app/lib/modules/login/login.dart
  app/lib/modules/login/presentation/cubit/login_cubit.dart
  app/lib/modules/login/presentation/presentation.dart
  app/lib/modules/login/presentation/view/login_view.dart
  app/lib/modules/login/presentation/view/sign_in_view.dart
  app/lib/modules/login/presentation/widgets/select_gender.dart
  app/lib/modules/login/presentation/widgets/select_lang.dart
  app/lib/modules/login/widget/widgets.dart
Labels: A1-bugfix, B1-medium, C0-breaksnothing

#203 Add package info plus & Implement detect untranslated localizations & Bump flutter v3.19.5 & Improve deployment process
  .github/ISSUE_TEMPLATE/release-testing.md
  .github/workflows/analyze_test.yml
  .github/workflows/build_android.yml
  .github/workflows/build_ios.yml
  .github/workflows/ci_android.yml
  .github/workflows/ci_ios.yml
  README.md
  app/android/app/build.gradle
  app/ios/Podfile.lock
  app/ios/Runner/Info.plist
  app/l10n.yaml
  app/l10n_errors.txt
  app/lib/app/data/repository/app_repositoty_impl.dart
  app/lib/app/data/source/app_local_data_source.dart
  app/lib/app/domain/domain.dart
  app/lib/app/domain/repository/app_repositoty.dart
  app/lib/app/domain/usecase/get_app_version_use_case.dart
  app/lib/app/presentation/cubit/app_cubit.dart
  app/lib/app/presentation/cubit/app_state.dart
  app/lib/app/presentation/view/app_view.dart
  app/lib/core/client/network_client.dart
  app/lib/l10n/arb/app_ar.arb
  app/lib/l10n/arb/app_en.arb
  app/lib/l10n/arb/app_id.arb
  app/lib/l10n/arb/app_kk.arb
  app/lib/l10n/arb/app_ky.arb
  app/lib/l10n/arb/app_ru.arb
  app/lib/l10n/arb/app_tr.arb
  app/lib/main.dart
  app/lib/modules/home/presentation/view/home_view.dart
  app/lib/modules/settings/presentation/view/settings_view.dart
  app/pubspec.lock
  app/pubspec.yaml
  app/test/helpers/pump_app.dart
  app/test/widget_test.dart
  packages/mq_storage/pubspec.yaml
  pubspec.lock
  pubspec.yaml
Labels: A2-technical, B2-priority, C0-breaksnothing

#202 changed quran module architecture
  app/lib/models/models.dart
  app/lib/modules/quran/data/data.dart
  app/lib/modules/quran/data/model/juz_model.dart
  app/lib/modules/quran/data/model/juz_model.g.dart
  app/lib/modules/quran/data/model/juz_surah_model.dart
  app/lib/modules/quran/data/model/juz_surah_model.g.dart
  app/lib/modules/quran/data/model/surah_model.dart
  app/lib/modules/quran/data/model/surah_model.g.dart
  app/lib/modules/quran/data/repository/quran_repository_impl.dart
  app/lib/modules/quran/data/source/juz_data.dart
  app/lib/modules/quran/data/source/juz_local_data_source.dart
  app/lib/modules/quran/data/source/surah_data.dart
  app/lib/modules/quran/data/source/surah_local_data_source.dart
  app/lib/modules/quran/domain/domain.dart
  app/lib/modules/quran/domain/entity/juz_entity.dart
  app/lib/modules/quran/domain/entity/juz_surah_entity.dart
  app/lib/modules/quran/domain/entity/surah_entity.dart
  app/lib/modules/quran/domain/repository/quran_repository.dart
  app/lib/modules/quran/domain/usecase/get_juzs.dart
  app/lib/modules/quran/domain/usecase/get_surahs.dart
  app/lib/modules/quran/logic/quran_cubit.dart
  app/lib/modules/quran/presentation/cubit/quran_cubit.dart
  app/lib/modules/quran/presentation/presentation.dart
  app/lib/modules/quran/presentation/view/page_view_item.dart
  app/lib/modules/quran/presentation/view/quran_view.dart
  app/lib/modules/quran/quran.dart
  app/lib/modules/quran_audio/logic/quran_audio_cubit.dart
Labels: A2-technical, B1-medium, C0-breaksnothing
