Repository Eldar2021/my_quran, pull requests merged in 2024-11, with the labels that each got.

#253 Changed hatim design
  app/lib/components/card/material_card.dart
  app/lib/l10n/arb/app_ky.arb
  app/lib/modules/hatim/data/model/hatim_page.dart
  app/lib/modules/hatim/presentation/presentation.dart
  app/lib/modules/hatim/presentation/view/hatim_select_page_view.dart
  app/lib/modules/hatim/presentation/view/hatim_view.dart
  app/lib/modules/hatim/presentation/widgets/hatim_juz_list_builder.dart
  app/lib/modules/hatim/presentation/widgets/hatim_page_status_card.dart
  app/lib/modules/hatim/presentation/widgets/hatim_status_widget.dart
  app/lib/modules/hatim/presentation/widgets/juz_annotation_widget.dart
  app/lib/modules/hatim/presentation/widgets/juz_percent_widget.dart
  app/lib/modules/hatim/presentation/widgets/progress_row_widget.dart
  app/lib/modules/hatim/presentation/widgets/vertical_text.dart
Labels: A0-ux, B1-medium, C0-breaksnothing

#254 Fix integration test error
  app/ios/Runner.xcodeproj/project.pbxproj
  app/ios/Runner/Info.plist
  app/lib/app/presentation/view/app_view.dart
  app/lib/modules/hatim/presentation/view/hatim_select_page_view.dart
  app/lib/modules/hatim/presentation/widgets/hatim_juz_list_builder.dart
  app/lib/modules/home/presentation/cubit/location_cubit.dart
  app/lib/modules/home/presentation/view/home_view.dart
  app/pubspec.lock
  app/test_driver/app/hatim/hatim_test.dart
  app/test_driver/app/settings/settings_test.dart
  app/test_driver/app_test.dart
Labels: A1-bugfix, B1-medium, C0-breaksnothing

#256 Integrate delete account
  app/lib/app/data/repository/auth_repositoty_impl.dart
  app/lib/app/data/source/auth_local_data_source.dart
  app/lib/app/data/source/auth_remote_data_source.dart
  app/lib/app/data/source/local/auth_local_data_source_impl.dart
  app/lib/app/data/source/mock/auth_local_data_source_mock.dart
  app/lib/app/data/source/mock/auth_remote_data_source_mock.dart
  app/lib/app/data/source/remote/auth_remote_data_source_impl.dart
  app/lib/app/domain/domain.dart
  app/lib/app/domain/repository/auth_repository.dart
  app/lib/app/domain/usecase/delete_account_use_case.dart
  app/lib/app/presentation/cubit/auth_cubit.dart
  app/lib/app/presentation/view/app_view.dart
  app/lib/components/alert/confirmation_dialog.dart
  app/lib/constants/api/api_const.dart
  app/lib/core/analytics/mq_analytic_keys.dart
  app/lib/core/auth/soccial_auth.dart
  app/lib/modules/settings/presentation/view/settings_view.dart
  app/lib/utils/show/alerts.dart
  app/test/helpers/pump_app.dart
  app/test/widget_test.dart
  packages/mq_ci_keys/lib/src/mq_ci_keys_base.dart
  packages/mq_remote_client/lib/src/mq_remote_client.dart
  packages/mq_remote_client/lib/src/mq_remote_client_base_extension.dart
Labels: A2-technical, B1-medium, C0-breaksnothing

#260 Fixed BottomNav always show & Fixed Settings twice navigation pop & Fixed onTap juz item
  app/lib/config/router/app_router.dart
  app/lib/modules/hatim/presentation/widgets/hatim_juz_list_builder.dart
  app/lib/modules/hatim/presentation/widgets/juz_annotation_widget.dart
  app/lib/modules/hatim/presentation/widgets/progress_row_widget.dart
  app/lib/modules/settings/presentation/view/settings_view.dart
Labels: A1-bugfix, B2-priority, C0-breaksnothing

#261 Add description to access location
  app/ios/Runner/Info.plist
Labels: A2-technical, B1-medium, C0-breaksnothing

#264 Added Contributing to MyQuran md
  CONTRIBUTING.md
Labels: A2-technical, B1-medium, C0-breaksnothing

#259 Integrate sign in with apple
  app/ios/Runner.xcodeproj/project.pbxproj
  app/lib/app/data/source/remote/auth_remote_data_source_impl.dart
  app/lib/core/auth/soccial_auth.dart
  app/lib/modules/login/presentation/view/sign_in_view.dart
  app/pubspec.yaml
Labels: A2-technical, B1-medium, C0-breaksnothing

#268 Release v1.3.4+14
  CHANGELOG.md
  app/pubspec.yaml
Labels: A2-technical, B1-medium, C0-breaksnothing
