Repository Eldar2021/my_quran, pull requests merged in 2024-12, with the labels that each got.

#269 Get app access without login
  app/ios/Podfile.lock
  app/lib/app/presentation/view/app_view.dart
  app/lib/config/config.dart
  app/lib/config/router/app_router.dart
  app/lib/config/router/navigation_helper.dart
  app/lib/l10n/arb/app_ar.arb
  app/lib/l10n/arb/app_en.arb
  app/lib/l10n/arb/app_id.arb
  app/lib/l10n/arb/app_kk.arb
  app/lib/l10n/arb/app_ky.arb
  app/lib/l10n/arb/app_ru.arb
  app/lib/l10n/arb/app_tr.arb
  app/lib/modules/home/presentation/view/home_view.dart
  app/lib/modules/login/presentation/view/sign_in_view.dart
  app/lib/modules/read/presentation/view/pagination_view.dart
  app/lib/modules/settings/presentation/view/about_us.dart
  app/lib/modules/settings/presentation/view/developers_view.dart
  app/lib/modules/settings/presentation/view/gender_settings.dart
  app/lib/modules/settings/presentation/view/settings_view.dart
Labels: A0-ux, B2-priority, C0-breaksnothing

#271 Release v1.3.5+15
  .github/ISSUE_TEMPLATE/release-testing.md
  CHANGELOG.md
  app/pubspec.yaml
Labels: A2-technical, B1-medium, C0-breaksnothing

#273 Skip CI if PR is draft
  .github/workflows/analyze_test.yml
  .github/workflows/build_android.yml
  .github/workflows/build_ios.yml
  .github/workflows/ci_android.yml
  .github/workflows/ci_ios.yml
Labels: A2-technical, B1-medium, C0-breaksnothing

#275 MqCrashlytics & MqAnalytics
  app/lib/app/data/repository/auth_repositoty_impl.dart
  app/lib/components/card/select_lang_list.dart
  app/lib/config/router/parse_parameters.dart
  app/lib/core/auth/soccial_auth.dart
  app/lib/core/core.dart
  app/lib/core/launch/app_launch.dart
  app/lib/main.dart
  app/lib/modules/dev_mode/presentation/dev_mode_view.dart
  app/lib/modules/hatim/data/source/remote/hatim_remote_data_source_impl.dart
  app/lib/modules/hatim/presentation/bloc/hatim_bloc.dart
  app/lib/modules/hatim/presentation/view/hatim_select_page_view.dart
  app/lib/modules/hatim/presentation/view/hatim_view.dart
  app/lib/modules/hatim/presentation/widgets/hatim_juz_list_builder.dart
  app/lib/modules/home/data/repository/home_repository_impl.dart
  app/lib/modules/home/presentation/cubit/home_cubit.dart
  app/lib/modules/home/presentation/view/home_view.dart
  app/lib/modules/login/presentation/view/login_view.dart
  app/lib/modules/login/presentation/view/sign_in_view.dart
  app/lib/modules/login/presentation/view/verification_code_view.dart
  app/lib/modules/login/presentation/widgets/select_gender.dart
  app/lib/modules/quran/presentation/view/page_view_item.dart
  app/lib/modules/quran_audio/logic/quran_audio_cubit.dart
  app/lib/modules/quran_audio/view/quran_audio_view.dart
  app/lib/modules/read/presentation/view/pagination_view.dart
  app/lib/modules/read/presentation/view/read_view.dart
  app/lib/modules/settings/presentation/view/gender_settings.dart
  app/lib/modules/settings/presentation/view/settings_view.dart
  app/lib/modules/settings/presentation/view/theme_settings.dart
  app/pubspec.lock
  app/pubspec.yaml
  app/pubspec_overrides.yaml
  packages/mq_analytics/README.md
  packages/mq_analytics/analysis_options.yaml
  packages/mq_analytics/lib/mq_analytics.dart
  packages/mq_analytics/lib/src/mq_analytics.dart
  packages/mq_analytics/lib/src/mq_analytics_keys.dart
  packages/mq_analytics/pubspec.yaml
  packages/mq_analytics/pubspec_overrides.yaml
  packages/mq_analytics/test/mq_analytics_test.dart
  packages/mq_crashlytics/README.md
  packages/mq_crashlytics/analysis_options.yaml
  packages/mq_crashlytics/lib/mq_crashlytics.dart
  packages/mq_crashlytics/lib/src/mq_crashlytics.dart
  packages/mq_crashlytics/pubspec.yaml
  packages/mq_crashlytics/test/mq_crashlytics_test.dart
Labels: A2-technical, B1-medium, C0-breaksnothing

#276 Remote config Package
  .github/workflows/analyze_test.yml
  .github/workflows/build_android.yml
  .github/workflows/build_ios.yml
  .github/workflows/ci_android.yml
  .github/workflows/ci_ios.yml
  app/ios/Podfile.lock
  app/lib/app/presentation/cubit/remote_config_cubit.dart
  app/lib/app/presentation/view/app_view.dart
  app/lib/core/core.dart
  app/lib/main.dart
  app/pubspec.lock
  app/pubspec.yaml
  app/pubspec_overrides.yaml
  app/test/helpers/pump_app.dart
  app/test/mocks/app_mocks.dart
  packages/mq_remote_config/README.md
  packages/mq_remote_config/analysis_options.yaml
  packages/mq_remote_config/lib/mq_remote_config.dart
  packages/mq_remote_config/lib/src/mq_remote_config.dart
  packages/mq_remote_config/pubspec.yaml
  packages/mq_remote_config/test/mock/mock_firebase_remote_config.dart
  packages/mq_remote_config/test/mq_remote_config_test.dart
Labels: A2-technical, B1-medium, C0-breaksnothing

#278 Added Play store and App store links
  README.md
  doc/images/app_store.png
  doc/images/google_play.png
Labels: A2-technical, B0-low, C0-breaksnothing

#277 Implement Home Repo Package
  app/lib/app/presentation/view/app_view.dart
  app/lib/constants/api/api_const.dart
  app/lib/main.dart
  app/lib/modules/home/cubit/home_cubit.dart
  app/lib/modules/home/cubit/home_state.dart
  app/lib/modules/home/cubit/location_cubit.dart
  app/lib/modules/home/cubit/location_state.dart
  app/lib/modules/home/data/data.dart
  app/lib/modules/home/data/source/home_local_data_source.dart
  app/lib/modules/home/data/source/home_remote_data_source.dart
  app/lib/modules/home/data/source/mock/home_local_data_source_mock.dart
  app/lib/modules/home/data/source/mock/home_remote_data_source_mock.dart
  app/lib/modules/home/data/source/remote/home_remote_data_source_impl.dart
  app/lib/modules/home/domain/domain.dart
  app/lib/modules/home/domain/repository/home_repository.dart
  app/lib/modules/home/domain/usecase/get_data_usecase.dart
  app/lib/modules/home/home.dart
  app/lib/modules/home/presentation/presentation.dart
  app/lib/modules/home/view/home_view.dart
  app/lib/modules/home/widgets/pray_time_widget.dart
  app/pubspec.lock
  app/pubspec.yaml
  app/pubspec_overrides.yaml
  app/test/helpers/pump_app.dart
  app/test/mocks/app_mocks.dart
  packages/mq_home_repository/README.md
  packages/mq_home_repository/analysis_options.yaml
  packages/mq_home_repository/lib/mq_home_repository.dart
  packages/mq_home_repository/lib/src/entity/mq_home_entity.dart
  packages/mq_home_repository/lib/src/model/mq_home_model_response.dart
  packages/mq_home_repository/lib/src/model/mq_home_model_response.g.dart
  packages/mq_home_repository/lib/src/repository/mq_home_repository.dart
  packages/mq_home_repository/lib/src/repository/mq_home_repository_impl.dart
  packages/mq_home_repository/lib/src/source/local/mq_home_local_data_source_impl.dart
  packages/mq_home_repository/lib/src/source/mock/mq_home_local_data_source_mock.dart
  packages/mq_home_repository/lib/src/source/mock/mq_home_remote_data_source_mock.dart
  packages/mq_home_repository/lib/src/source/mq_home_local_data_source.dart
  packages/mq_home_repository/lib/src/source/mq_home_remote_data_source.dart
  packages/mq_home_repository/lib/src/source/remote/mq_home_remote_data_source_impl.dart
  packages/mq_home_repository/lib/src/src.dart
  packages/mq_home_repository/pubspec.yaml
  packages/mq_home_repository/pubspec_overrides.yaml
  packages/mq_home_repository/test/mq_home_repository_test.dart
Labels: A2-technical, B1-medium, C0-breaksnothing

#284 Fixed build runner error CI
  .github/workflows/analyze_test.yml
  app/pubspec_overrides.yaml
  melos.yaml
  scripts/delete_g_files.sh
Labels: A1-bugfix, B2-priority, C0-breaksnothing

#283 Remove presentation folder
  app/lib/modules/dev_mode/dev_mode.dart
  app/lib/modules/dev_mode/view/dev_mode_view.dart
  app/lib/modules/login/cubit/login_cubit.dart
  app/lib/modules/login/login.dart
  app/lib/modules/login/presentation/presentation.dart
  app/lib/modules/login/view/login_view.dart
  app/lib/modules/login/view/sign_in_view.dart
  app/lib/modules/login/view/verification_code_view.dart
  app/lib/modules/login/widgets/select_gender.dart
  app/lib/modules/login/widgets/select_lang.dart
  app/lib/modules/main/main.dart
  app/lib/modules/main/view/main_view.dart
  app/lib/modules/quran_audio/cubit/quran_audio_cubit.dart
  app/lib/modules/quran_audio/cubit/quran_audio_state.dart
  app/lib/modules/quran_audio/quran_audio.dart
  app/lib/modules/settings/presentation/presentation.dart
  app/lib/modules/settings/settings.dart
  app/lib/modules/settings/view/about_us.dart
  app/lib/modules/settings/view/contact_us.dart
  app/lib/modules/settings/view/developers_view.dart
  app/lib/modules/settings/view/gender_settings.dart
  app/lib/modules/settings/view/lang_settings.dart
  app/lib/modules/settings/view/settings_view.dart
  app/lib/modules/settings/view/theme_settings.dart
  app/lib/modules/settings/widgets/contact_us_card.dart
  app/lib/modules/settings/widgets/social_icon_button.dart
  app/lib/modules/settings/widgets/widgets.dart
Labels: A2-technical, B1-medium, C0-breaksnothing

#288 Release v1.3.7+17
  CHANGELOG.md
  app/ios/Runner.xcodeproj/project.pbxproj
  app/pubspec.yaml
Labels: A2-technical, B1-medium, C0-breaksnothing
